language: android
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    #- platform-tools
    #- tools

    # The BuildTools version used by your project
    - build-tools-23.0.3

    # The SDK version used to compile your project
    - android-23

    # Additional components
    #- extra-google-google_play_services
    #- extra-google-m2repository
    - extra-android-m2repository
    #- addon-google_apis-google-19

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    #- sys-img-armeabi-v7a-android-19
    #- sys-img-x86-android-17

before_install:
    - echo $ANDROID_HOME
    - rm -rf $NVM_DIR ~/.npm ~/.bower
    - echo Y | sudo apt-get remove --purge node nodejs npm 
    - echo Y | curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
    - echo Y | sudo apt-get install -y nodejs build-essential
    - node -v
    - npm -v
    - sudo npm install -g react-native
    - npm install
    - react-native run-android
    #- ./node_modules/react-native/packager/packager.sh & 

install:
    - cd android; ./gradlew build

